#ifndef N_SAMPLE
#define N_SAMPLE 3
#endif

//== Define Pins ==//
//Potentiometers
#define OMEGA_FEEDBACK_PIN GPIO_NUM_36
#define OMEGA_FEEDBACK_ADC ADC1_CHANNEL_0

#define OMEGA_INPUT_PIN GPIO_NUM_39
#define OMEGA_INPUT_ADC ADC1_CHANNEL_3

#define KP_PIN GPIO_NUM_34
#define KP_ADC ADC1_CHANNEL_6

#define KI_PIN GPIO_NUM_35
#define KI_ADC ADC1_CHANNEL_7

#define KD_PIN GPIO_NUM_32
#define KD_ADC ADC1_CHANNEL_4

#define COEF_COUNT 3

//Motors
#define MOTOR_IN1 GPIO_NUM_25
#define MOTOR_IN2 GPIO_NUM_26

//I2C
#define CONFIG_SDA_GPIO  21
#define CONFIG_SCL_GPIO  22
#define CONFIG_LCD_ADDR 0x27
#define CONFIG_I2C_CLK_FREQ 100000
#define CONFIG_LCD_COLUMNS 16
#define CONFIG_LCD_ROWS 2
